// Copyright Istio Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//    http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"
	json "encoding/json"
	"fmt"

	v1alpha1 "istio.io/client-go/pkg/apis/extensions/v1alpha1"
	extensionsv1alpha1 "istio.io/client-go/pkg/applyconfiguration/extensions/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeServiceMetadatas implements ServiceMetadataInterface
type FakeServiceMetadatas struct {
	Fake *FakeExtensionsV1alpha1
	ns   string
}

var servicemetadatasResource = schema.GroupVersionResource{Group: "extensions.istio.io", Version: "v1alpha1", Resource: "servicemetadatas"}

var servicemetadatasKind = schema.GroupVersionKind{Group: "extensions.istio.io", Version: "v1alpha1", Kind: "ServiceMetadata"}

// Get takes name of the serviceMetadata, and returns the corresponding serviceMetadata object, and an error if there is any.
func (c *FakeServiceMetadatas) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.ServiceMetadata, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(servicemetadatasResource, c.ns, name), &v1alpha1.ServiceMetadata{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ServiceMetadata), err
}

// List takes label and field selectors, and returns the list of ServiceMetadatas that match those selectors.
func (c *FakeServiceMetadatas) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.ServiceMetadataList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(servicemetadatasResource, servicemetadatasKind, c.ns, opts), &v1alpha1.ServiceMetadataList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.ServiceMetadataList{ListMeta: obj.(*v1alpha1.ServiceMetadataList).ListMeta}
	for _, item := range obj.(*v1alpha1.ServiceMetadataList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested serviceMetadatas.
func (c *FakeServiceMetadatas) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(servicemetadatasResource, c.ns, opts))

}

// Create takes the representation of a serviceMetadata and creates it.  Returns the server's representation of the serviceMetadata, and an error, if there is any.
func (c *FakeServiceMetadatas) Create(ctx context.Context, serviceMetadata *v1alpha1.ServiceMetadata, opts v1.CreateOptions) (result *v1alpha1.ServiceMetadata, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(servicemetadatasResource, c.ns, serviceMetadata), &v1alpha1.ServiceMetadata{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ServiceMetadata), err
}

// Update takes the representation of a serviceMetadata and updates it. Returns the server's representation of the serviceMetadata, and an error, if there is any.
func (c *FakeServiceMetadatas) Update(ctx context.Context, serviceMetadata *v1alpha1.ServiceMetadata, opts v1.UpdateOptions) (result *v1alpha1.ServiceMetadata, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(servicemetadatasResource, c.ns, serviceMetadata), &v1alpha1.ServiceMetadata{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ServiceMetadata), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeServiceMetadatas) UpdateStatus(ctx context.Context, serviceMetadata *v1alpha1.ServiceMetadata, opts v1.UpdateOptions) (*v1alpha1.ServiceMetadata, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(servicemetadatasResource, "status", c.ns, serviceMetadata), &v1alpha1.ServiceMetadata{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ServiceMetadata), err
}

// Delete takes name of the serviceMetadata and deletes it. Returns an error if one occurs.
func (c *FakeServiceMetadatas) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(servicemetadatasResource, c.ns, name, opts), &v1alpha1.ServiceMetadata{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeServiceMetadatas) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(servicemetadatasResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.ServiceMetadataList{})
	return err
}

// Patch applies the patch and returns the patched serviceMetadata.
func (c *FakeServiceMetadatas) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.ServiceMetadata, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(servicemetadatasResource, c.ns, name, pt, data, subresources...), &v1alpha1.ServiceMetadata{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ServiceMetadata), err
}

// Apply takes the given apply declarative configuration, applies it and returns the applied serviceMetadata.
func (c *FakeServiceMetadatas) Apply(ctx context.Context, serviceMetadata *extensionsv1alpha1.ServiceMetadataApplyConfiguration, opts v1.ApplyOptions) (result *v1alpha1.ServiceMetadata, err error) {
	if serviceMetadata == nil {
		return nil, fmt.Errorf("serviceMetadata provided to Apply must not be nil")
	}
	data, err := json.Marshal(serviceMetadata)
	if err != nil {
		return nil, err
	}
	name := serviceMetadata.Name
	if name == nil {
		return nil, fmt.Errorf("serviceMetadata.Name must be provided to Apply")
	}
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(servicemetadatasResource, c.ns, *name, types.ApplyPatchType, data), &v1alpha1.ServiceMetadata{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ServiceMetadata), err
}

// ApplyStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating ApplyStatus().
func (c *FakeServiceMetadatas) ApplyStatus(ctx context.Context, serviceMetadata *extensionsv1alpha1.ServiceMetadataApplyConfiguration, opts v1.ApplyOptions) (result *v1alpha1.ServiceMetadata, err error) {
	if serviceMetadata == nil {
		return nil, fmt.Errorf("serviceMetadata provided to Apply must not be nil")
	}
	data, err := json.Marshal(serviceMetadata)
	if err != nil {
		return nil, err
	}
	name := serviceMetadata.Name
	if name == nil {
		return nil, fmt.Errorf("serviceMetadata.Name must be provided to Apply")
	}
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(servicemetadatasResource, c.ns, *name, types.ApplyPatchType, data, "status"), &v1alpha1.ServiceMetadata{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ServiceMetadata), err
}
